### ISSUE TITLE
ssearch not working

### ISSUE THREAD

**Issue by Handymanalan** [yosuken/ccfind#1]
Hi Yosuke,

I was using the program but I got the error

> batch/04-1/prepare_ssearch.1: line 24: ssearch: command not found
rake aborted!
Command failed with status (127): [sh batch/04-1/prepare_ssearch.1...]
/srv/scratch/z3336178/ccfind/ccfind.rake:27:in `block (2 levels) in <top (required)>'
/srv/scratch/z3336178/ccfind/ccfind.rake:19:in `each'
/srv/scratch/z3336178/ccfind/ccfind.rake:19:in `block in <top (required)>'
/srv/scratch/z3336178/ccfind/ccfind.rake:272:in `block in <top (required)>'
/srv/scratch/z3336178/ccfind/ccfind.rake:112:in `block (2 levels) in <top (required)>'
/srv/scratch/z3336178/ccfind/ccfind.rake:111:in `each'
/srv/scratch/z3336178/ccfind/ccfind.rake:111:in `with_index'
/srv/scratch/z3336178/ccfind/ccfind.rake:111:in `block in <top (required)>'

Is it because the correct command line should be **ssearch36** instead of just **ssearch**?

Thanks for looking into it.

Cheers

Alan

**Comment by yosuken** [comment]
Hi Alan,

Thank you for your suggestion. 
I thought ssearch exists as symlink to ssearch36, but I realized that this is only the case for my environment...
Now scripts are updated. From v1.4.4, the scripts use ssearch36 instead of ssearch.

Yosuke

**Comment by Handymanalan** [comment]
Thanks Yosuke it's working now.

Cheers

Alan
