### ISSUE TITLE
Aborted on step 11/13  (04-6.prodigal_for_circ)

### ISSUE THREAD

**Issue by bishav6708** [yosuken/ccfind#2]
Hello,
when running the ccfind command in a fasta file without any detected circular contigs, the command executes successfully. However, when I tried to run the command in a fasta file with possible circular contigs, I get the following error. 

step 11 / 13 (04-6.prodigal_for_circ) -- START
mkdir -p batch/04-6/log_parallel
parallel --jobs 10 --joblog batch/04-6/log_parallel/prodigal_for_circ.1 <batch/04-6/prodigal_for_circ.1
rake aborted!
Command failed with status (8): [parallel --jobs 10 --joblog batch/04-6/log...]
/tools/ccfind/ccfind.rake:25:in `block (2 levels) in <top (required)>'
/tools/ccfind/ccfind.rake:19:in `each'
/tools/ccfind/ccfind.rake:19:in `block in <top (required)>'
/tools/ccfind/ccfind.rake:386:in `call'
/tools/ccfind/ccfind.rake:386:in `block in <top (required)>'
/tools/ccfind/ccfind.rake:112:in `block (2 levels) in <top (required)>'
/tools/ccfind/ccfind.rake:111:in `each'
/tools/ccfind/ccfind.rake:111:in `with_index'
/tools/ccfind/ccfind.rake:111:in `block in <top (required)>'
Tasks: TOP => 04-6.prodigal_for_circ
(See full trace by running task with --trace)

Can you help me figure this out.

P.S. I have the latest version cloned in my terminal.

Thanks!

**Comment by yosuken** [comment]
HI bishav6708

I'm sorry for missing this issue for a long time...
The reported case is reproduced when a number of circular sequences is less than a number specified by --ncpus.

I got fixed the bug. Please update to the latest version.

Thank you very much for reporting this issue.
